"""phase 2 training content

Revision ID: 20260606_phase2
Revises: d3bc26c2606f
Create Date: 2026-06-06 14:18:21.646596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '20260606_phase2'
down_revision: Union[str, Sequence[str], None] = 'd3bc26c2606f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_muscle', sa.String(length=120), nullable=False),
    sa.Column('difficulty', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tutorial_url', sa.String(length=500), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('detection_rules', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_library_id'), 'exercise_library', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_library_slug'), 'exercise_library', ['slug'], unique=True)
    op.create_table('workout_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_calories_per_hour', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_modes_code'), 'workout_modes', ['code'], unique=True)
    op.create_index(op.f('ix_workout_modes_id'), 'workout_modes', ['id'], unique=False)
    op.create_table('leaderboard_refresh_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=40), nullable=False),
    sa.Column('metric_type', sa.String(length=60), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_type', 'metric_type', 'period_start', name='uq_leaderboard_refresh_state_period_metric')
    )
    op.create_index(op.f('ix_leaderboard_refresh_states_id'), 'leaderboard_refresh_states', ['id'], unique=False)
    op.create_index(op.f('ix_leaderboard_refresh_states_metric_type'), 'leaderboard_refresh_states', ['metric_type'], unique=False)
    op.create_index(op.f('ix_leaderboard_refresh_states_period_end'), 'leaderboard_refresh_states', ['period_end'], unique=False)
    op.create_index(op.f('ix_leaderboard_refresh_states_period_start'), 'leaderboard_refresh_states', ['period_start'], unique=False)
    op.create_index(op.f('ix_leaderboard_refresh_states_period_type'), 'leaderboard_refresh_states', ['period_type'], unique=False)
    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=40), nullable=False),
    sa.Column('metric_type', sa.String(length=60), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_type', 'metric_type', 'period_start', 'user_id', name='uq_leaderboard_snapshot_period_metric_user')
    )
    op.create_index(op.f('ix_leaderboard_snapshots_id'), 'leaderboard_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_metric_type'), 'leaderboard_snapshots', ['metric_type'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_period_end'), 'leaderboard_snapshots', ['period_end'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_period_start'), 'leaderboard_snapshots', ['period_start'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_period_type'), 'leaderboard_snapshots', ['period_type'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_user_id'), 'leaderboard_snapshots', ['user_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_mode_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_mode_id'], ['workout_modes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_id'), 'workout_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_leaderboard_snapshots_user_id'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_period_type'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_period_start'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_period_end'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_metric_type'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_id'), table_name='leaderboard_snapshots')
    op.drop_table('leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_refresh_states_period_type'), table_name='leaderboard_refresh_states')
    op.drop_index(op.f('ix_leaderboard_refresh_states_period_start'), table_name='leaderboard_refresh_states')
    op.drop_index(op.f('ix_leaderboard_refresh_states_period_end'), table_name='leaderboard_refresh_states')
    op.drop_index(op.f('ix_leaderboard_refresh_states_metric_type'), table_name='leaderboard_refresh_states')
    op.drop_index(op.f('ix_leaderboard_refresh_states_id'), table_name='leaderboard_refresh_states')
    op.drop_table('leaderboard_refresh_states')
    op.drop_index(op.f('ix_workout_modes_id'), table_name='workout_modes')
    op.drop_index(op.f('ix_workout_modes_code'), table_name='workout_modes')
    op.drop_table('workout_modes')
    op.drop_index(op.f('ix_exercise_library_slug'), table_name='exercise_library')
    op.drop_index(op.f('ix_exercise_library_id'), table_name='exercise_library')
    op.drop_table('exercise_library')
    # ### end Alembic commands ###
